### PR TITLE
Bump kubernetes deps to v1.29.0

### PR DESCRIPTION
**Pull request by liangyuanpeng**
~~Bump kubernetes deps to v1.28.4,In order to ensure that the project is consistent with kubernetes dependencies,i will create two PR after this PR is merged.~~

~~1. cherrypick this to release-0.28~~
~~2. Bump kubernetes deps to v1.29.0~~

Bump kubernetes deps to v1.29.0

### CODE REVIEW

**Comment by jkh52** [comment]
We likely need to update https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/apiserver-network-proxy/apiserver-network-proxy-presubmits.yaml#L11 for golang 1.21

**Comment by liangyuanpeng** [comment]
Just back from vacation and closed due to duplicate with https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/565.

**Pull request closed without merging**
