### PR TITLE
Upgrade github.com/prometheus/client_golang to help unblock dependabot.

### PR DESCRIPTION
**Pull request by jkh52**
Help unblock dependabot and enable the 0.31 release.

$ go get github.com/prometheus/client_golang@v1.20.4
$ go mod tidy
$ go mod vendor

Fix test fallout.

### CODE REVIEW

**Comment by cheftako** [comment]
Rerunning lint to see if the new kubekins image has helped with the lint error.

**Comment by bwplotka** [comment]
FYI: We reverted the problematic change in https://github.com/prometheus/client_golang/releases/tag/v1.20.5, sorry for pain!

**Comment by jkh52** [comment]
> FYI: We reverted the problematic change in https://github.com/prometheus/client_golang/releases/tag/v1.20.5, sorry for pain!

Thanks for the heads up! I verified that v1.20.5 resolves our dependabot issue. I will close this workaround PR.

**Pull request closed without merging**
