### PR TITLE
Make sure deps are clean prior to running update vendor.

### PR DESCRIPTION
**Pull request by cheftako**
Update instructions to ensure K/K dependencies are clean before running update vendor.

### CODE REVIEW

**Comment by Jefftree** [comment]
Just out of curiosity what was the scenario in which this was needed? Network proxy doesn't have any code generation in k/k so if we start from a clean workspace, upgrade network proxy and run update-vendor, I don't see any reason the generated files would change.

**Comment by cheftako** [comment]
> Just out of curiosity what was the scenario in which this was needed? Network proxy doesn't have any code generation in k/k so if we start from a clean workspace, upgrade network proxy and run update-vendor, I don't see any reason the generated files would change.

https://github.com/kubernetes/kubernetes/pull/106188#discussion_r743898778 is an example. I ended up with spurious changes in the go.mod file. Running the clean and then the update vendor fixed it. I assume this is from have older generated files lying around.

**Pull request merged**
