### PR TITLE
proxy-server: in gRPC mode, set same keepalive for UDS and mTLS.

### PR DESCRIPTION
**Pull request by jkh52**
Fix an inconsistency that was identified in #276

### CODE REVIEW

**Comment by jkh52** [comment]
/retest

TestFailedDial_HTTPCONN seems like a flake (only modifed gRPC codepath)

**Comment by cheftako** [comment]
> TestFailedDial_HTTPCONN seems like a flake (only modifed gRPC codepath)
Worrying. Would be good to capture the error and fix at some point. If you see this again, can you capture the failure in a bug?

**Comment by rata** [comment]
Thanks!

Sorry, with @ipochi we were waiting for confirmation if this helped or not before opening the PR!

**Comment by rata** [comment]
@jkh52 Just curious, do you happen to know if the keepalive was not used for the UDS case before on purpose?

By looking at the git history, it seems the keepalive config was _never_ there for the UDS case and I'm not sure if the grpc PING command (that the keepalive.Time config sends), that AFAIK uses the http/2 ping command underneath, works over UDS sockets. Do you happen to know? I guess it does, but not _sure_.

I agree, though, that this won't probably hurt in any way, though, and seems like it was forgotten. But we were trying to validate that before opening the PR, we can open the PR without doing those things the next time :)

**Pull request merged**
