### PR TITLE
Fix segfault on empty packet

### PR DESCRIPTION
**Pull request by ncopa**
Verify if pkt is nil before logging the type.

### CODE REVIEW

**Comment by jkh52** [comment]
This looks like a clear improvement, but the if block seems "unreachable" (because in agent.pb.go, if err is nil, packet should not be: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/proto/agent/agent.pb.go#L107).

/lgtm
/ok-to-test

**Comment by jkh52** [comment]
@ncopa, see previous comment - was this fix based on code inspection, or did you actually observe a segfault?

**Comment by ncopa** [comment]
> @ncopa, see previous comment - was this fix based on code inspection, or did you actually observe a segfault?

Code inspection. Maybe I should change the commit message to be less dramatic? "Fix potential segfault on empty packet"

Another option is to remove the log line since it is unreachable (and thus dead code). In any case, the current order things happen does not make any sense.

**Comment by cheftako** [comment]
> if block seems "unreachable"
If the block is unreachable then we should not need the 'if pkt nil' check. As long as we have it, I think logging pkt.type statement should come after the nil check.

**Comment by ncopa** [comment]
> > if block seems "unreachable"
> 
> If the block is unreachable then we should not need the 'if pkt nil' check. As long as we have it, I think logging pkt.type statement should come after the nil check.

This is exactly the point here.

**Comment by ncopa** [comment]
I re-based it against current master.

**Pull request merged**
