### PR TITLE
Cosmetic: avoid "ctx" naming confusion.

### PR DESCRIPTION
**Pull request by jkh52**
Cosmetic only: rename `connContext` to `endpointConn`.

### CODE REVIEW

**Comment by tallclair** [comment]
/lgtm
/hold

There are a lot of PRs in flight right now. You may want to wait to submit this to avoid merge conflicts. Feel free to /unhold when you're ready.

**Comment by jkh52** [comment]
/remove-hold

@tallclair this does merge cleanup enough into release-0.0 that I think we can allow it to merge. PTAL

**Comment by jkh52** [comment]
make lint timed out:

```
level=info msg="[runner] linters took 43.496576689s with stages: goanalysis_metalinter: 43.470680481s"
level=info msg="fixer took 0s with no stages"
level=info msg="File cache stats: 0 entries of total size 0B"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

/retest

**Pull request merged**
