### PR TITLE
edit invalid link

### PR DESCRIPTION
**Pull request by yanyhui**
ref #208

### CODE REVIEW

**Comment by yanyhui** [comment]
I signed it

**Comment by cheftako** [comment]
For the CLA issue (https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement):
Guessing the email on your git commit(s) does not match the email you used for the CLA. You can fix the email address on your git commit as follows. You may also want to squash your commits first.

$ git config --global user.email "email@example.com"
$ git commit --amend --reset-author

Then you should be able to just push your change again.

If you encounter any problems signing the CLA, log a ticket with the Linux Foundation ID group through the (Linux Foundation Support Site)[https://support.linuxfoundation.org/].

**Pull request closed without merging**
