### PR TITLE
Update server and agent images to Go version 1.19.6

### PR DESCRIPTION
**Pull request by jkh52**
Context: https://groups.google.com/g/golang-announce/c/2zqu2BOnpP8/m/3ECQJP56AwAJ

Reference similar for k/k: https://github.com/kubernetes/release/issues/2909

### CODE REVIEW

**Comment by jkh52** [comment]
```
make[1]: Entering directory '/home/prow/go/src/sigs.k8s.io/apiserver-network-proxy'
protoc -I . proto/agent/agent.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=require_unimplemented_servers=false:. --go-grpc_opt=paths=source_relative
make[1]: protoc: No such file or directory
```

This flake happens (but rarely) ever since https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/434

/retest

**Comment by jkh52** [comment]
/assign @tallclair

I hope to get this into next release tag

**Comment by tallclair** [comment]
Should we update the go.mod file too? https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/go.mod#L3

**Comment by jkh52** [comment]
> Should we update the go.mod file too? https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/go.mod#L3

Done. It doesn't feel good to keep konnectivity-client/go.mod on 1.17, but let's handle it separately.

**Pull request merged**
