### PR TITLE
Make certs gen work on macOS Catalina

### PR DESCRIPTION
**Pull request by jieyu**
Before this patch, `make certs` does not work on macOS Catalina.

Even after downloading the darwin version of the binary, the `cfssl`
will still throw runtime errors like the following:

```
failed MSpanList_Insert 0x246000 0x1f2a23e9f33a9 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x15d320, 0x10)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff280 sp=0x7ffeefbff268
```

This patch fixed the issue by skipping downloading the cfssl and
cfssljson if those commands are already installed on the host (e.g.,
through brew install).

Tested on macOS Catalina.

### CODE REVIEW

**Comment by cheftako** [comment]
Great job getting this working on Catalina and nice clean up as well, thanks for the help!

**Comment by jieyu** [comment]
Anything I need to do to get this merged?

**Comment by cheftako** [comment]
Sorry my fault, I thought the PR had the relevant permissions.

**Pull request merged**
