### PR TITLE
Fix lint: move to Github Action

### PR DESCRIPTION
**Pull request by jkh52**
Update golangci-lint from 1.54.0 to v1.56.2, per needed for go1.22 per https://github.com/golangci/golangci-lint/issues/4273.

Introduce a Github Action based linter.

Fix resulting findings.

### CODE REVIEW

**Comment by jkh52** [comment]
Now, golangci-lint appears to succeed but then "hangs". Any ideas, @liangyuanpeng or @cheftako ?

**Comment by jkh52** [comment]
The lint authors recommend using Github Actions: https://golangci-lint.run/welcome/install/#ci-installation

This works for me, see latest snapshot.

**Comment by jkh52** [comment]
Although `pull-apiserver-network-proxy-make-lint-master` continues to fail, see the successful `golangci-lint / lint (pull_request)`.

/retest

**Comment by jkh52** [comment]
@cheftako friendly ping.

It would be nice to get lint working again against mainline. I would have liked to simply adjust Makefile but I never solved a remaining mystery why it hangs when invoked from kubekins / test-infra. At the same linter version it succeeds very quickly via Github Action. Migrating lint to Github Actions might be superior going forward, even if we did not have that mystery.

**Comment by liangyuanpeng** [comment]
I first tried to reproduce it in the local /github action, but with no luck, I am trying to test it by upgrading golangci-lint to 1.59.0 in https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/664

**Pull request merged**
