### PR TITLE
update to latest go to pickup critical http2 connection fixes

### PR DESCRIPTION
**Pull request by relyt0925**
This investigation done in Kubernetes has more details on the specific fixes:
 kubernetes/kubernetes#87615

There's critical failure paths in lower go versions below 1.15 where http2 connections when faced with certain network/connection errors can deadlock on open connections. The connections are left open but whenever a write or read is done from one it will log `: use of closed network connection` and do nothing.

I confirmed this behavior exists in the latest proxy:
```
Tylers-MacBook-Pro:armada-ansible tylerlisowski$ kubectl logs -n master-52643725 konnectivity-agent-8c6699584-nj6lk | grep 172.21.107.127
I0625 18:56:37.448913       1 options.go:98] AgentIdentifiers set to ipv4=172.21.224.93,ipv4=172.21.107.127,ipv4=172.21.161.36.
E0625 18:56:41.248418       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58694->172.21.107.127:443: use of closed network connection"
E0625 18:56:41.248676       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58694->172.21.107.127:443: use of closed network connection" connectionID=22
E0625 18:56:41.618133       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58712->172.21.107.127:443: use of closed network connection"
E0625 18:56:41.618396       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58712->172.21.107.127:443: use of closed network connection" connectionID=29
E0625 18:56:41.631325       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58724->172.21.107.127:443: use of closed network connection"
E0625 18:56:42.452451       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58746->172.21.107.127:443: use of closed network connection"
E0625 18:56:42.452548       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58746->172.21.107.127:443: use of closed network connection" connectionID=45
E0625 18:57:13.675144       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58872->172.21.107.127:443: use of closed network connection"
E0625 18:57:13.676248       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58872->172.21.107.127:443: use of closed network connection" connectionID=47
E0625 18:57:14.130623       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58980->172.21.107.127:443: use of closed network connection" connectionID=60
E0625 18:57:14.132805       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58990->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.133007       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58980->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.133256       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58990->172.21.107.127:443: use of closed network connection" connectionID=65
E0625 18:57:14.133962       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59002->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.134045       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59002->172.21.107.127:443: use of closed network connection" connectionID=70
E0625 18:57:14.134200       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59004->172.21.107.127:443: use of closed network connection" connectionID=71
E0625 18:57:14.134280       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59004->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.134815       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59012->172.21.107.127:443: use of closed network connection" connectionID=75
E0625 18:57:14.134882       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59012->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.135142       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59008->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.135599       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59024->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.135953       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59014->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.136198       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59008->172.21.107.127:443: use of closed network connection" connectionID=73
E0625 18:57:14.136333       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59014->172.21.107.127:443: use of closed network connection" connectionID=76
E0625 18:57:14.136364       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59024->172.21.107.127:443: use of closed network connection" connectionID=81
E0625 18:57:14.136687       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59018->172.21.107.127:443: use of closed network connection" connectionID=78
E0625 18:57:14.136728       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59018->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.137144       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59022->172.21.107.127:443: use of closed network connection" connectionID=80
E0625 18:57:14.137172       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59022->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.144878       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59028->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.145312       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59028->172.21.107.127:443: use of closed network connection" connectionID=83
E0625 18:57:14.153871       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59034->172.21.107.127:443: use of closed network connection" connectionID=85
E0625 18:57:14.153943       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59034->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.157825       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59044->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.158068       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59050->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.158858       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59044->172.21.107.127:443: use of closed network connection" connectionID=90
E0625 18:57:14.158887       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59050->172.21.107.127:443: use of closed network connection" connectionID=93
E0625 18:57:14.172726       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59070->172.21.107.127:443: use of closed network connection" connectionID=103
E0625 18:57:14.172733       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59070->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.176887       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59072->172.21.107.127:443: use of closed network connection" connectionID=104
E0625 18:57:14.177031       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59072->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.196796       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59078->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.196876       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59078->172.21.107.127:443: use of closed network connection" connectionID=107
E0625 18:57:14.204150       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59088->172.21.107.127:443: use of closed network connection" connectionID=112
E0625 18:57:14.204159       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59088->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.233412       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59110->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.234193       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59110->172.21.107.127:443: use of closed network connection" connectionID=123
E0625 18:57:14.236235       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59116->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.236377       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59116->172.21.107.127:443: use of closed network connection" connectionID=126
E0625 18:57:14.244415       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59120->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.244527       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59120->172.21.107.127:443: use of closed network connection" connectionID=128
E0625 18:57:14.244607       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59122->172.21.107.127:443: use of closed network connection" connectionID=129
E0625 18:57:14.244623       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59122->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.244826       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59124->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.244880       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59124->172.21.107.127:443: use of closed network connection" connectionID=130
E0625 18:57:14.244983       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59126->172.21.107.127:443: use of closed network connection" connectionID=131
E0625 18:57:14.245119       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59126->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.245367       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59128->172.21.107.127:443: use of closed network connection" connectionID=132
E0625 18:57:14.245458       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59128->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.245652       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59130->172.21.107.127:443: use of closed network connection" connectionID=133
E0625 18:57:14.245671       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59130->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.245852       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59132->172.21.107.127:443: use of closed network connection" connectionID=134
E0625 18:57:14.245873       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59132->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.250748       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59170->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.256059       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59170->172.21.107.127:443: use of closed network connection" connectionID=153
E0625 18:57:14.257161       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59218->172.21.107.127:443: use of closed network connection" connectionID=177
E0625 18:57:14.257268       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59218->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.257763       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59222->172.21.107.127:443: use of closed network connection" connectionID=179
E0625 18:57:14.257821       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59222->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.258942       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59230->172.21.107.127:443: use of closed network connection" connectionID=183
E0625 18:57:14.259080       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59230->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.259506       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59234->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.259557       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59234->172.21.107.127:443: use of closed network connection" connectionID=185
E0625 18:57:14.261622       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59250->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.262382       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59250->172.21.107.127:443: use of closed network connection" connectionID=193
E0625 18:57:14.277376       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59336->172.21.107.127:443: use of closed network connection" connectionID=236
E0625 18:57:14.277518       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59336->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.290270       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59348->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.290291       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59348->172.21.107.127:443: use of closed network connection" connectionID=242
E0625 18:57:14.290457       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59350->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.290491       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59350->172.21.107.127:443: use of closed network connection" connectionID=243
E0625 18:57:14.290635       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59354->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.290791       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59354->172.21.107.127:443: use of closed network connection" connectionID=245
E0625 18:57:14.294079       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59364->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.294136       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59364->172.21.107.127:443: use of closed network connection" connectionID=250
E0625 18:57:14.323421       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59420->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.324344       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59420->172.21.107.127:443: use of closed network connection" connectionID=278
E0625 18:57:14.331369       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59446->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.331794       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59434->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.332213       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59438->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.332953       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59444->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.333275       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59446->172.21.107.127:443: use of closed network connection" connectionID=291
E0625 18:57:14.333356       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59434->172.21.107.127:443: use of closed network connection" connectionID=285
E0625 18:57:14.333420       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59438->172.21.107.127:443: use of closed network connection" connectionID=287
E0625 18:57:14.333515       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59444->172.21.107.127:443: use of closed network connection" connectionID=290
E0625 18:57:14.397667       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59542->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.398521       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59744->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.398856       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59462->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.413390       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59562->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.413757       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59742->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.415410       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59492->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.415778       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59468->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.416448       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59468->172.21.107.127:443: use of closed network connection" connectionID=302
E0625 18:57:14.416493       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59492->172.21.107.127:443: use of closed network connection" connectionID=314
E0625 18:57:14.418337       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59482->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.418355       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59482->172.21.107.127:443: use of closed network connection" connectionID=309
E0625 18:57:14.419169       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59532->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.419563       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59584->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.420384       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59532->172.21.107.127:443: use of closed network connection" connectionID=334
E0625 18:57:14.420783       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59584->172.21.107.127:443: use of closed network connection" connectionID=360
E0625 18:57:14.429355       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59738->172.21.107.127:443: use of closed network connection" connectionID=436
E0625 18:57:14.429498       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59738->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.429716       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59464->172.21.107.127:443: use of closed network connection" connectionID=300
E0625 18:57:14.429809       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59464->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.442582       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59582->172.21.107.127:443: use of closed network connection"
E0625 18:57:14.442641       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59582->172.21.107.127:443: use of closed network connection" connectionID=359
E0625 18:58:10.849754       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58662->172.21.107.127:443: use of closed network connection"
E0625 18:58:10.849791       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58662->172.21.107.127:443: use of closed network connection" connectionID=7
E0625 18:58:21.479721       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58678->172.21.107.127:443: use of closed network connection"
E0625 18:58:21.479817       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:58678->172.21.107.127:443: use of closed network connection" connectionID=14
E0625 19:03:16.502406       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58696->172.21.107.127:443: use of closed network connection"
E0625 19:05:01.229725       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:58688->172.21.107.127:443: use of closed network connection"
E0625 19:05:12.272453       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59794->172.21.107.127:443: use of closed network connection"
E0625 19:05:12.272560       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59794->172.21.107.127:443: use of closed network connection" connectionID=453
E0625 19:05:39.553271       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59818->172.21.107.127:443: use of closed network connection"
E0625 19:05:39.553274       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59818->172.21.107.127:443: use of closed network connection" connectionID=458
E0625 19:05:47.717615       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59804->172.21.107.127:443: use of closed network connection"
E0625 19:06:07.946095       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59808->172.21.107.127:443: use of closed network connection"
E0625 19:06:07.946187       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59808->172.21.107.127:443: use of closed network connection" connectionID=457
E0625 19:07:19.860683       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59796->172.21.107.127:443: use of closed network connection"
E0625 19:07:30.152719       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:59910->172.21.107.127:443: use of closed network connection"
E0625 19:07:30.152730       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:59910->172.21.107.127:443: use of closed network connection" connectionID=459
E0625 19:09:08.741180       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:36662->172.21.107.127:443: use of closed network connection"
E0625 19:09:08.741214       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:36662->172.21.107.127:443: use of closed network connection" connectionID=468
E0625 19:11:50.496757       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:38470->172.21.107.127:443: use of closed network connection"
E0625 19:11:50.496932       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:38470->172.21.107.127:443: use of closed network connection" connectionID=480
E0625 19:12:16.160974       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:38366->172.21.107.127:443: use of closed network connection"
E0625 19:12:19.756953       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:38308->172.21.107.127:443: use of closed network connection"
E0625 19:12:19.756971       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:38308->172.21.107.127:443: use of closed network connection" connectionID=474
E0625 19:12:30.944067       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:36776->172.21.107.127:443: use of closed network connection"
E0625 19:13:18.613387       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:36788->172.21.107.127:443: use of closed network connection"
E0625 19:13:18.613459       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:36788->172.21.107.127:443: use of closed network connection" connectionID=472
E0625 19:13:51.246140       1 client.go:473] "connection read failure" err="read tcp 172.30.210.115:36650->172.21.107.127:443: use of closed network connection"
E0625 19:13:51.246172       1 client.go:502] "conn write failure" err="write tcp 172.30.210.115:36650->172.21.107.127:443: use of closed network connection" connectionID=465
```

### CODE REVIEW

**Comment by relyt0925** [comment]
Only way to fix with the existing go is to restart the components.

**Comment by cheftako** [comment]
I believe we will need to tag and generate new server and agent to pick this up.

**Comment by caesarxuchao** [comment]
lgtm

**Comment by relyt0925** [comment]
Kubernetes issue is:
https://github.com/kubernetes/kubernetes/issues/87615

**Comment by relyt0925** [comment]
Confirmed this fixed the issue for me as well

**Comment by relyt0925** [comment]
Note this pr will be needed as well to enable the health checking https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/248

**Comment by relyt0925** [comment]
@cheftako @caesarxuchao 

could we get an approved label?

**Comment by antoninbas** [comment]
I'm seeing the exact same error messages with the latest released version of the server & agent (v0.0.22, built with go1.16).

```
$ kubectl -n kube-system describe pods/konnectivity-agent-8162e52c-c63e-4745-b5fd-9680c115a0eb-75blspj | grep Image
    Image:         k8s.gcr.io/kas-network-proxy/proxy-agent:v0.0.22
```

```
$ kubectl -n kube-system logs konnectivity-agent-8162e52c-c63e-4745-b5fd-9680c115a0eb-75blspj | grep E0
E0727 23:21:24.437343       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55386->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.438246       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55368->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.438732       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55362->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.439238       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55366->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.445068       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55368->192.168.113.3:10349: use of closed network connection" connectionID=4
E0727 23:21:24.535906       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55362->192.168.113.3:10349: use of closed network connection" connectionID=1
E0727 23:21:24.535959       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55366->192.168.113.3:10349: use of closed network connection" connectionID=3
E0727 23:21:24.637743       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55380->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.637905       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55380->192.168.113.3:10349: use of closed network connection" connectionID=10
E0727 23:21:24.637929       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55378->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638100       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55364->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638226       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55364->192.168.113.3:10349: use of closed network connection" connectionID=2
E0727 23:21:24.638328       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55382->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638209       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55378->192.168.113.3:10349: use of closed network connection" connectionID=9
E0727 23:21:24.638615       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55370->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638789       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55390->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638976       1 client.go:486] "connection read failure" err="read tcp 192.168.113.4:55384->192.168.113.3:10349: use of closed network connection"
E0727 23:21:24.638520       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55382->192.168.113.3:10349: use of closed network connection" connectionID=11
E0727 23:21:24.639305       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55370->192.168.113.3:10349: use of closed network connection" connectionID=5
E0727 23:21:24.639391       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55384->192.168.113.3:10349: use of closed network connection" connectionID=12
E0727 23:21:24.639338       1 client.go:515] "conn write failure" err="write tcp 192.168.113.4:55390->192.168.113.3:10349: use of closed network connection" connectionID=15
```

Is this expected? Based on the PR description, my understanding was that these errors were symptomatic of using an old Go version.

**Comment by mihivagyok** [comment]
@antoninbas Is it possible we need this PR too?
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/248

Thank you!

**Comment by antoninbas** [comment]
@mihivagyok thanks for the ping. It's possible, I won't know until v0.0.23 is released and I have a chance to test it :)

**Comment by weitzj** [comment]
We are running into the same issues using Kubernetes 1.20.8 (or 1.20.10). Do you have an idea when 0.0.23 will be available?

Kubernetes 1.20.10 uses v0.0.22

**Comment by cheftako** [comment]
@weitzj Are you looking for server/agents images to be available or having the v0.0.23 client code used in the KAS? (Sorry just planning)

**Comment by weitzj** [comment]
I guess I would need it in the Kubernetes apiserver. I would have to check what that means regarding of our use of Kops (I.e. how does handle kops minor Kubernetes versions). I know in kops I can set a Kubernetes version 1.20.11 and do a rolling upgrade, but I am not sure what artifacts I would need from Kubernetes

**Comment by cheftako** [comment]
I'll start the ball rolling on that. We've been working on a flaky test in the scalability tests and I was hoping to get that to land in 0.0.23 but no need to make you wait. I will go ahead and get that rolling. I would hope this would land in KAS head pretty quickly. Can't speak to how long it will take to get the fix cherry picked back to 1.20.

**Comment by weitzj** [comment]
Thanks a bunch. So I would need

sigs.k8s.io/apiserver-network-proxy/konnectivity-client: v0.0.22 → v0.0.23

as a dependency upgrade here: https://github.com/kubernetes/kubernetes/tree/v1.20.10

as mentioned in the change log.

Do I have to trigger the maintainers? Do you do it? It looks like 1.20.11-rc1 is already out. So I can hope for a 1.20.12 version.

thanks again

**Pull request merged**
