### PR TITLE
chore: update actions upload-artifact & download-artifact to v4.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Resolve #598 and #597

### CODE REVIEW

**Comment by jkh52** [comment]
> Resolve #598 and #597

Both this PR and these two from dependabot have e2e failures, I haven't looked into it. @liangyuanpeng

**Comment by liangyuanpeng** [comment]
the first problem is upload-artifact and download-artifact need to update with the same time,  it's resoved by the first commit of this PR.

The second problem is that the name of the log artifact lacks the k8s version, which leads to the problem of repeatedly uploading artifacts.It's resoved by the second commit.

All of CI is green now, tested on my fork repo.

**Pull request merged**
