### PR TITLE
fix Makefile commands

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by Sh4d1** [comment]
@cheftako should fix the push job

**Comment by Sh4d1** [comment]
@cheftako good to merge?

**Comment by cheftako** [comment]
Good :D

**Comment by Sh4d1** [comment]
I don't have the rights to merge though 😅

**Comment by cheftako** [comment]
Merging. Definitely agree we should have an over-ride for the docker command.

**Comment by Sh4d1** [comment]
Crap, still failing, I'll push a PR tomorrow to fix it 😅

**Pull request merged**
